[package]
name = "qbit_gluetun_port"
version = "0.1.0"
edition = "2021"

[dependencies]
qbit-rs = "0.4.6"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.96"
dotenvy = "0.15.7"
env_logger = "0.11.5"
result_logger = "0.1.1"
log = "0.4.22"
logcall = "0.1.11"